#!/bin/bash
#SBATCH --account=jbq@a100
#SBATCH --constraint=a100
#SBATCH --job-name=Apply_LLavastro
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --hint=nomultithread

#SBATCH --qos=qos_gpu-dev
#SBATCH --time=05:00:00



module purge
module load cuda/11.7.1 nccl/2.12.12-1-cuda 
module load cudnn/8.5.0.96-11.7-cuda 
module load gcc/8.5.0 openmpi/4.1.1-cuda 
module load intel-mkl/2020.4 
module load magma/2.7.0-cuda 
module load sox/14.4.2 sparsehash/2.0.3 
module load libjpeg-turbo/2.1.3 python/3.9.12

export PYTHONUSERBASE=$ALL_CCFRWORK/galaxy_zoo/.local_sample
export PATH=/gpfswork/rech/owt/commun/galaxy_zoo/.local_sample/bin/:$PATH


srun python -u \
$WORK/2023-galaxy-zoo-llm/scripts/apply_llavastro.py \
--model-name /gpfswork/rech/owt/commun/LLaVA-13B-v0 \
--image-folder /gpfsscratch/rech/owt/commun/galaxy_zoo \
--answers-file $WORK/Data/answer.jsonl \
--N_ans 100